### ISSUE TITLE
Question about player's selector

### ISSUE THREAD

**Issue by localmidia** [clappr/clappr-level-selector-plugin#3]
Hi,

The plugin isn't working for me. Appears only auto option, not allowing me to choose between the bitrates.

Can you help me?

Plaese, see my example: http://www.localmidia.com.br/flash/clappr/player.html

Note: I tested in Safari (HTML5 Mode) and Chrome/Firefox (Flash mode)

Regards,
![safari](https://cloud.githubusercontent.com/assets/11320475/8111648/59b986b8-1039-11e5-80f2-bb060b99d250.jpg)
![chrome](https://cloud.githubusercontent.com/assets/11320475/8111649/59e2bfba-1039-11e5-9afa-962fc63ed391.jpg)

**Comment by sfarges** [comment]
Hello, I get the same issue: only Auto appears and clicking on auto trigger this error in console : "Uncaught TypeError: this.getContainer(...).playback.el.globoPlayerSmoothSetLevel is not a function"

- Player is using scripts: 
  src="http://cdn.clappr.io/latest/clappr.js"
  src="http://cdn.jsdelivr.net/clappr.level-selector/latest/level-selector.min.js"
- Client is Chrome Version 44.0.2403.39 beta or Firefox 38.0 running on ubuntu 15.04
- Target video is HLS m3u8 linking to 3 qualities

Compatibility issue with last version of flashHLS ?

Regards,

**Comment by Canardlaquay** [comment]
Same problem here, using the latest version of clappr.min.js (from the CDN). I've tried the cdn version of level-selector.min.js and the one one on the repo, didn't change anything, I only see the "auto" option. (I do see the HD tag though)

**Comment by d3vilmayc4y** [comment]
+1

**Comment by tarkanlar** [comment]
@towerz is there anything we can check or update to fix this?

**Comment by towerz** [comment]
@tarkanlar and others, I just pushed a new tag (0.0.7) that works with the latest clappr version (0.1.13). 

There was a bug on the previous clappr version that wasn't triggering the level change event. There was another bug in the plugin, which was calling the wrong functions to check and select the current level.

It was already pushed to jsdelivr, so the sample code at http://www.localmidia.com.br/flash/clappr/player.html will work correctly after the changes propagate throughout the CDN. The only problem with that is that the HLS source is not available anymore, it seems.

**Comment by sfarges** [comment]
@towerz , thank you, problem solved (with the version 0.0.7 and 0.1.13).
  <script type="text/javascript" src="http://cdn.clappr.io/0.1.13/clappr.js"></script>
  <script type="text/javascript" src="http://cdn.jsdelivr.net/clappr.level-selector/0.0.7/level-selector.min.js"></script>

**Comment by tarkanlar** [comment]
@towerz thanks. I was in vacation i just could test works like a charm

**Comment by towerz** [comment]
Glad it's working now.

I released version 0.0.8 of the plugin working now with Clappr version 0.2.2. With these versions the `baseUrl` parameter is not necessary anymore, since the default URL points now to the versioned URL.

I'll close this issue now. Thank you all!
